### ISSUE TITLE
Le segnalazioni sono per aule o strumenti

### ISSUE THREAD

**Issue by leo93921** [leo93921/university.be#2]
Le specifiche riportano: **_oppure di segnalare problematiche alla segreteria (del tipo, l’aula è troppo piccola, il proiettore non funziona, la wifi perde spesso la connessione, ecc.)_**

Nel DB, nella tabella reporting, invece, abbiamo che le colonne _item_ e _classroom_ sono entrambe NOT NULL.

**Comment by gianlucaalfa** [comment]
Le segnalazioni sono sempre per l'aula.
Esempi: -segnalo che nell'aula Y1 non funziona il WiFi.
-segnalo che nell'aula M4 non funziona il proiettore.

Quindi, per come la vedo io, non è una segnalazione "per aule o strumenti". Ma una segnalazione "di strumenti nell'aula"

Quindi item è obbligatorio e classroom pure.
